easy_admin:
    site_name: 'Panel administracyjny'
    design:
        form_theme: ['@EasyAdmin/form/bootstrap_4.html.twig', '@VichUploader/Form/fields.html.twig']
        menu:
            - { label: 'Strona główna', route: 'home_page', icon: 'home' }
            - { label: 'Encje' }
            - Qualification
            - Stage
            - Question
            - { label: 'Zaawansowane' }
            - { label: 'Wyczyść cache', route: 'clear_cache', icon: 'trash' }
            - { label: 'Wydobądź pytania', route: 'optain_exam', icon: 'car' }
    entities:
        Qualification:
            class: App\Entity\Qualification
            new:
                title: 'Dodaj kwalifikacje'
                label: 'Kwalifikacje'
            label: 'Kwalifikacje'
            list:
                title: '%%entity_label%%'
                fields:
                    - id
                    - { property: 'designation', label: 'Kod' }
                    - { property: 'description', label: 'Opis' }
            form:
                fields:
                    - { property: 'designation', type: 'text', label: 'Kod'}
                    - { property: 'description', type: 'textarea', label: 'Opis' }
                    - { property: 'friendlyUrl', type: "text", label: 'Przyjazny link' }
                    - { property: 'metaDescription', type: "textarea", label: 'Opis meta' }
                    - { property: 'stages' }

        Stage:
            class: App\Entity\Stage
            new:
                title: 'Dodaj etap'
                fields:
                    - { property: 'designation', type: "text", label: 'Nazwa' }
                    - { property: 'friendlyUrl', type: "text", label: 'Przyjazny link' }
                    - { property: 'metaDescription', type: "textarea", label: 'Opis meta' }
                    - { property: 'qualifications' }
                    - { property: 'imageFile', label: 'Zdjęcie', type: 'vich_image'}
            label: 'Etapy'
            list:
                title: 'Etapy'
                fields:
                    - id
                    - { property: 'designation', label: 'Opis' }
            edit:
                title: 'Edytuj etap'
                fields:
                    - { property: 'designation', type: "text", label: 'Nazwa' }
                    - { property: 'friendlyUrl', type: "text", label: 'Przyjazny link' }
                    - { property: 'metaDescription', type: "textarea", label: 'Opis meta' }
                    - { property: 'qualifications' }
                    - { property: 'imageFile', label: 'Zdjęcie', type: 'vich_image', type_options: { allow_delete: false }}


        Question:
            class: App\Entity\Question
            new:
                title: 'Dodaj pytanie'
            label: 'Pytania zamknięte'
            list:
                title: '%%entity_label%%'
                fields:
                    - id
                    - { property: 'query', label: 'Pytanie' }
                    - { property: 'answerA', label: 'Odpowiedź A' }
                    - { property: 'answerB', label: 'Odpowiedź B' }
                    - { property: 'answerC', label: 'Odpowiedź C' }
                    - { property: 'answerD', label: 'Odpowiedź D' }
                    - { property: 'correct', label: 'Poprawna' }
                    - { property: 'qualification', label: 'Kwalifikacja' }
            form:
                fields:
                    - { property: 'query', label: 'Pytanie', type: 'fos_ckeditor' }
                    - { property: 'answerA', label: 'Odpowiedź A', type: 'fos_ckeditor' }
                    - { property: 'answerB', label: 'Odpowiedź B', type: 'fos_ckeditor' }
                    - { property: 'answerC', label: 'Odpowiedź C', type: 'fos_ckeditor' }
                    - { property: 'answerD', label: 'Odpowiedź D', type: 'fos_ckeditor' }
                    - { property: 'correct', label: 'Poprawna', type: 'choice', type_options: { choices: { 'A': '1', 'B': '2', 'C': '3', 'D': '4' } } }
                    - { property: 'qualification', label: 'Kwalifikacja' }
                    - { property: 'session', label: 'Sesja', type: 'choice', type_options: { choices: { 'Letnia': 'letnia', 'Zimowa': 'zimowa'} } }
                    - { property: 'year', label: 'Rok', type: 'choice', type_options: { choices: { '2013': '2013', '2014': '2014', '2015': '2015', '2016': '2016', '2017': '2017', '2018': '2018', '2019': '2019' } } }
                    - { property: 'imageFile', label: 'Zdjęcie', type: 'vich_image' }